version: '3'
services:
#  front:
#    image: ui
##    build:
##      context: .
#    environment:
#      API_HOST: http://localhost:8001/api
#    ports:
#      - 80:80
#    depends_on:
#      - server
  server:
    build:
      context: .
    environment:
      POSTGRES_HOST: postgres
      TOKEN_KEY: mytokenstring
      POSTGRES_DB: provider
    ports:
      - 8001:8001
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=Initial0
    volumes:
      - pg4:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432


volumes:
  pg4:
