version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=Initial0
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg:
